//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Core.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Core.Exceptions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string CODE_200 {
            get {
                return ResourceManager.GetString("CODE_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 201.
        /// </summary>
        public static string CODE_201 {
            get {
                return ResourceManager.GetString("CODE_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 204.
        /// </summary>
        public static string CODE_204 {
            get {
                return ResourceManager.GetString("CODE_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string CODE_400 {
            get {
                return ResourceManager.GetString("CODE_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.
        /// </summary>
        public static string CODE_401 {
            get {
                return ResourceManager.GetString("CODE_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403.
        /// </summary>
        public static string CODE_403 {
            get {
                return ResourceManager.GetString("CODE_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string CODE_500 {
            get {
                return ResourceManager.GetString("CODE_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host = 47.241.69.179;Database = MISA.CukCuk_Demo_NVMANH;User id = dev;Password = 12345678;.
        /// </summary>
        public static string connectionString {
            get {
                return ResourceManager.GetString("connectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã trùng với khách hàng khác trong tệp nhập khẩu..
        /// </summary>
        public static string CUS_CODE_EXIST_IN_FILE_MSG {
            get {
                return ResourceManager.GetString("CUS_CODE_EXIST_IN_FILE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm khách hàng không có trong hệ thống..
        /// </summary>
        public static string CUS_GROUP_NOT_EXIST_MSG {
            get {
                return ResourceManager.GetString("CUS_GROUP_NOT_EXIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa dữ liệu thành công !!.
        /// </summary>
        public static string DELETE_SUCCESS_MSG {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng bị trùng !!.
        /// </summary>
        public static string EXCEPTION_ERR_DULICATE_CUSTOMERCODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_DULICATE_CUSTOMERCODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban bị trùng.
        /// </summary>
        public static string EXCEPTION_ERR_DULICATE_DEPARTMENTCODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_DULICATE_DEPARTMENTCODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên bị trùng !!.
        /// </summary>
        public static string EXCEPTION_ERR_DULICATE_EMPLOYEECODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_DULICATE_EMPLOYEECODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí bị trùng !!.
        /// </summary>
        public static string EXCEPTION_ERR_DULICATE_POSITIONCODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_DULICATE_POSITIONCODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng !!.
        /// </summary>
        public static string EXCEPTION_ERR_EMAIL_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_EMAIL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra! vui lòng liên hệ với MISA..
        /// </summary>
        public static string EXCEPTION_ERR_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được phép để trống !!.
        /// </summary>
        public static string EXCEPTION_ERR_NULL_CUSTOMERCODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_NULL_CUSTOMERCODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được phép để trống !!.
        /// </summary>
        public static string EXCEPTION_ERR_NULL_DEPARTMENTCODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_NULL_DEPARTMENTCODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống !!.
        /// </summary>
        public static string EXCEPTION_ERR_NULL_EMPLOYEECODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_NULL_EMPLOYEECODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí không được phép để trống !!.
        /// </summary>
        public static string EXCEPTION_ERR_NULL_POSITIONCODE_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_ERR_NULL_POSITIONCODE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn file nhập khẩu hoặc file nhập khẩu bị lỗi !.
        /// </summary>
        public static string FILE_EMPTY_MSG {
            get {
                return ResourceManager.GetString("FILE_EMPTY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu gửi lên không đúng định dạng !!.
        /// </summary>
        public static string IMPORT_DATA_NOT_CORRECT_FORMAT_MSG {
            get {
                return ResourceManager.GetString("IMPORT_DATA_NOT_CORRECT_FORMAT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng file không được hỗ trợ !.
        /// </summary>
        public static string NOT_SUPPORT_FILE_EXT_MSG {
            get {
                return ResourceManager.GetString("NOT_SUPPORT_FILE_EXT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT đã tồn tại trong hệ thống..
        /// </summary>
        public static string PHONE_NUMBER_DULICATE_MSG {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_DULICATE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT đã trùng với SĐT của khách hàng khác trong tệp nhập khẩu..
        /// </summary>
        public static string PHONE_NUMBER_EXIST_IN_FILE_MSG {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_EXIST_IN_FILE_MSG", resourceCulture);
            }
        }
    }
}
